workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Prepare Android project
        script: |
          # android klasörü yoksa oluştur
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
          flutter pub get
      - name: Build APK
        script: |
          flutter clean
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  android-aab:
    name: Build Android AppBundle (Play Store)
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Prepare Android project
        script: |
          # android klasörü yoksa oluştur
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
          flutter pub get
      - name: Build AAB
        script: |
          flutter clean
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
