workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: 3.13.9
      java: 17
    scripts:
      - name: Prepare Android project
        script: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
          flutter pub get
      - name: Build APK (release)
        script: |
          flutter clean
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
