name: islamic_app
description: İslami Yaşam Uygulaması
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^10.1.0
  flutter_compass: ^0.7.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
